### ISSUE TITLE
Create project documentation on wiki

### ISSUE THREAD

**Issue by sunbiz** [iupui-soic/dynaswap#22]
Please use the wiki to document the different parts of our project and checkmark the following or add more, as an when you get those done

- [x] Introduction about our project (not too technical)
- [x] The overall project architecture
- [x] Explaining the different parts of the GitHub codebase
- [ ] How to deploy the image into a JetStream VM
- [ ] How to add users to share a VM
- [x] Release notes for different versions of the openmrs-base images
- [ ] Future Roadmap

**Comment by shreyagoyal1** [comment]
https://github.com/shreyagoyal1/dynaswap.wiki.git

**Comment by sunbiz** [comment]
@shreyagoyal1 needs more work on the deploying image to JetStream, adding users to VM, and future roadmap.

**Comment by sunbiz** [comment]
Merged shreya changes. Updated release to v1.4
