### ISSUE TITLE
Create a framework for integration-tests to get CVSS score

### ISSUE THREAD

**Issue by sunbiz** [iupui-soic/dynaswap#23]
We need to develop a framework, using the Behavior Driven Development (BDD) approach so that all of our security enhancements to JetStream VMs can be evaluated and a CVSS score can be generated.

Once the framework is ready, we need some examples that can generate baseline scores for plain OpenMRS.

**Comment by shreyagoyal1** [comment]
Yes, professor. I have uploaded the gherkin file and pytest-bdd for evaluating the OpenMRS authentication with 3 different cases: incorrect username, incorrect username and password, and incorrect password attempts. Using the parameters from CVSS, the score is calculated for all the cases. This example will create a baseline score for authentication to plain OpenMRS and can be used later to calculate the CVSS score once the security enhancements are made.

**Comment by sunbiz** [comment]
Thanks @shreyagoyal1 for the framework commits.
