### ISSUE TITLE
Fix registering issue when user with multiple roles registers for facial authentication 

### ISSUE THREAD

**Issue by shreyagoyal1** [iupui-soic/dynaswap#36]
When the user tries to register for facial authentication with multiple roles like for example admin user with two roles: system developer and provider, choosing either of the two roles is unable to match the user, gives Unknown Username/Role combination error.

**Comment by sunbiz** [comment]
Other than the admin user, whose userid is "null" for some reason in the database, other users are working fine and can register. Closing this as fixed.
Thanks, Tyler.
